version: "3.8"
services:
  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka
    ports:
      - "8761:8761"

  userservice:
    image: userservice
    build: ./UserService/userservice
    container_name: userservice
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
    ports:
      - "9000:8080"
    depends_on:
      - "userserviceDB"

  userserviceDB:
    image: mongo
    container_name: userserviceDB
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  
  appointmentservice:
    image: appointmentservice
    build: ./AppiontmentServiceApi
    container_name: appointmentservice
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
    ports:
      - "9001:8080"
    depends_on:
      - "userserviceDB"
      
  appointmentdb:
    image: sql-image
    build: ./AppointmentServiceApi/appointmentdb
    container_name: sql-appointment
    ports:
      - "1500:1433"

  apigateway:
    image: apigateway:1    
    container_name: apigateway
    build:
      context: ./ApiGateway
      dockerfile: 2.dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka

  #DEBUG USER SERVICE MONGO DATABASE
  #Opens a portal on port 8081 to access the mongo database
  #nicer than using mongo compass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=userserviceDB

# networks:
#   default:
#     name: netSEN3
#     external: true