version: "3.8"
services:

  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka
    ports:
      - "8761:8761"
  

  userservice:
    image: userservice
    build: ./UserService/userservice
    container_name: userservice
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
    ports:
      - "9000:8080"
    depends_on:
      - userserviceDB
      - eureka

  userserviceDB:
    image: mongo
    container_name: userserviceDB
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  
  appointmentdb:
    image: sql-image
    build: .\db
    container_name: sql-appointment
    ports:
      - "1500:1433"

  appointmentservice:
    image: appointmentservice
    build: ./AppointmentServiceApi
    container_name: appointmentservice
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
    ports:
      - "9001:8080"
    depends_on:
      - appointmentdb
      - eureka
  
  jobservice:
    image: jobservice
    build: ./JobService
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
    ports:
      - 9002:8080
    depends_on:
      - jobdb
      - eureka

  jobdb:
    image: sql-image
    container_name: sql-appointment
    ports:
      - "1501:1433"
    

  socketserver:
    image: socketserver
    build: ./socketserver
    ports:
      - "5000:5000"
    depends_on:
      - eureka
  
  apigateway:
    image: apigateway:1    
    container_name: apigateway
    build:
      context: ./ApiGateway
      dockerfile: 2.dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka