server:
  port: 8888
 
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      routes:
      - id: basketService
        uri: lb://BASKETSERVICE
        predicates:
        - Path=/basket/**
        
      - id: cardService
        uri: lb://CARDSERVICE
        predicates:
        - Path=/card/**

      - id: catalogService
        uri: lb://CATALOGSERVICE 
        predicates:
        - Path=/catalog/**        
        #you can now hit this api gateway via: http://localhost:8888/api1/abc

      - id: checkoutService
        uri: lb://CHECKOUTSERVICE
        predicates:
        - Path=/checkout/**
        #you can now hit endpoint like: http://localhost:8888/test1 this somehow maps to the minimal api endpoints

      - id: userService
        uri: lb://USERSERVICE
        predicates:
        - Path=/user/**
        #you can now hit http://localhost:8888/api2