server:
  port: 8888

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      routes:
      #User Service
      - id: userService
        uri: lb://USERSERVICE
        predicates:
        - Path=/user/**
      #Appointment Service
      - id: appointmentService
        uri: lb://APPOINTMENTSERVICE
        predicates:
        - Path=/appointment/**
      #Job Service
      - id: jobService
        uri: lb://JOBSERVICE
        predicates:
        - Path=/job/**