server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      routes:
      - id: appointmentService
        uri: lb://APPOINTMENTSERVICE
        predicates:
        - Path=/appointment/**
        